### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by viswanathreddy** [observing/fullcontact#23]
npm install fullcontact --save 
gives the following error:
npm ERR! fetch failed https://registry.npmjs.org/fullcontact/-/fullcontact-1.0.0.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 503

My internet is working fine. So no network issues

**Comment by 3rd-Eden** [comment]
This is an npm issue and not something that is caused by this module. See their status page:

https://twitter.com/npmstatus/status/795575490186649601

> [status] Investigating: we are seeing elevated 503s from our cdns singapore pop.

**Comment by viswanathreddy** [comment]
@3rd-Eden thanks for the quick reply !
