### ISSUE TITLE
Certain emails just spin and nothing is ever returned

### ISSUE THREAD

**Issue by toymachiner62** [observing/fullcontact#5]
I'm playing around with this library and I have this code snippet and if i use the name "jeff@gmail.com" it returns data fast and if i use the name "dick@gmail.com" it just spins and never returns  (at least not in 4 minutes).

```js
fullcontact.person.email('jeff@gmail.com', function(err, fcData) {
			
	if(err) {
		return Boom.badRequest(err);
	}
	
        // NEVER GETS HERE WITH "dick@gmail.com"
	console.log(fcData);
})
```

Any ideas on this?

**Comment by AdriVanHoudt** [comment]
@toymachiner62 is it possible fullcontact is searching for results because it doesn't know that email yet? try using the webhooks instead

**Comment by toymachiner62** [comment]
It's been a while since i looked at this so i don't believe so. If it doesn't know the email it should return either no data or the err var should contain a message that there is no data. It should never just not return.

**Comment by AdriVanHoudt** [comment]
true, normally fullcontact will always return see ![](https://fullcontact-static.s3.amazonaws.com/images/website/person-diagram.png)
