### ISSUE TITLE
Company

### ISSUE THREAD

**Issue by 3rd-Eden** [observing/fullcontact#8]
Support the newly introduced Company API:

https://www.fullcontact.com/developer/docs/company/

**Comment by AdriVanHoudt** [comment]
@3rd-Eden do you mind if I take this? This is a desired feature in my company so I will probably even take a shot at this today

**Comment by 3rd-Eden** [comment]
@AdriVanHoudt Feel free to take it. It would be user simple to implement as they only have domain lookups atm.

**Comment by AdriVanHoudt** [comment]
cool thanks
