### ISSUE TITLE
1.0.0

### ISSUE THREAD

**Issue by AdriVanHoudt** [observing/fullcontact#9]
@observing/full-contact-write 
Can we move to following semver? We have been using this lib for a while and it seems to work just fine so I would like to propose to move to v1.0.0 once we add the company api.

**Comment by 3rd-Eden** [comment]
Sounds good to me.

**Comment by AdriVanHoudt** [comment]
:+1:

**Comment by AdriVanHoudt** [comment]
Ok so 1.0.0 would include
* cleanup (#10)
* company api (#11)
At this time, any suggestions welcome!
Btw @3rd-Eden I kinde need v1.0.0 asap so if you could review what I did asap that would greatly help me out, thanks!

**Comment by 3rd-Eden** [comment]
Released 1.0.0

**Comment by AdriVanHoudt** [comment]
That was quick haha I'll make sure the webhook stuff is available on all
endpoints as wel and update the docs with the company info
